on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: wattpad/github-workflows/.github/workflows/go-test-and-build.yml@main
    secrets: inherit
    with:
      golangci_version: "v1.52.1"
      api_type: GRPC